# Generated by Django 5.1.4 on 2024-12-06 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer360', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='social_media',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
